### PR TITLE
Fix: Add a check for tektonconfig status

### LINKED ISSUE #167: [BUG] Operator reports "Ready: True" when TektonConfig reports "Error"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kubernetes Version

v1.25 or higher

### Shipwright Version

v0.12.0 (and earlier)

### Current Behavior

When the TektonConfig object (existing, or created by the Shipwright operator) reports its status as Error/not available, the ShipwrightBuild object only reports its status condition as "Ready: True".

### Expected Behavior

`ShipwrightBuild` should either report a status condition of "Ready: False", or report a new status condition like "Available" which is used to convey the overall health of the system.

### Steps To Reproduce

1. Deploy OLM on Kubernetes 1.25 or higher (ex - with KinD)
2. Deploy the Shipwright Operator using the operatorhub.io catalog - ensure it uses Tekton Operator v0.61 or lower
3. Create a `ShipwrightBuild` instance

### Anything else?

Related to https://github.com/tektoncd/operator/issues/1493 - the Tekton Operator in operatorhub is currently obsolete and breaks on k8s 1.25 or higher.

### PR DESCRIPTION
**Pull request by hasanawad94**
# Changes

Added a check for tektonconfig before progressing in the reconciliation process.

Fixes #167

# Submitter Checklist

- [ x ] Includes tests if functionality changed/was added
- [ ] Includes docs if changes are user-facing
- [ ] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)
- [ x ] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/main/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes
```
Fix: build status reports ready early when tektonconfig is at Error/not available state
```

### CODE REVIEW

**Comment by hasanawad94** [comment]
Test still needs fixing

File: controllers/shipwrightbuild_controller.go [hunk 1]
```diff
@@ -104,6 +104,44 @@ func deleteObjectsIfPresent(ctx context.Context, k8sClient client.Client, objs [
 	return nil
 }
 
+// Check and fetch TektonConfig
+func (r *ShipwrightBuildReconciler) fetchAndCheckTektonConfig(ctx context.Context, logger logr.Logger, b *v1alpha1.ShipwrightBuild) (bool, error) {
+	tektonConfig, err := r.TektonOperatorClient.TektonConfigs().Get(ctx, "config", metav1.GetOptions{})
+	if err != nil {
```
Comment (adambkaplan) [inline controllers/shipwrightbuild_controller.go:110]: Please differentiate between the "not found" error and other types of errors:

```suggestion
	tektonConfig, err := r.TektonOperatorClient.TektonConfigs().Get(ctx, "config", metav1.GetOptions{})
	if kerrors.IsNotFound(err) {
```

We can get other types of errors trying to get data from the kube apiserver (including timeouts). These we typically do not record to status because they are transient. TektonConfig missing is something that is more permanent and might require intervention from a cluster admin.

**Review by adambkaplan — CHANGES_REQUESTED** [review]
/approve

Code changes generally look good. Asking for a few changes before we call this good to merge:

1. Add the check for not found errors
2. Update the commit message so it is more complete. Tekton has an excellent guide on [writing good commit messages](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages).

**Comment by hasanawad94** [comment]
Cleaning up tests

**Comment by hasanawad94** [comment]
I have updated some tests to create the tektonconfig since its status being ready is now required after the fix

**Review by adambkaplan — COMMENTED** [review]
/approve

Marking this as a fix worth adding.

/hold

There is a bit of risk with this change, I'd rather not merge it as we are getting ready for the v0.16.0 release. After we release v0.16.0 I think it's fine to merge.

**Comment by adambkaplan** [comment]
The e2e appeared to have flaked - timed out waiting for the operator pod to become ready. We may consider increasing the timeout from 5m to 10 or 15 minutes...

**Review by adambkaplan — COMMENTED** [review]
Code wise this looks good. However, I do ask that you fix the typos and formatting of the commit message. These serve as excellent reference for future maintainers (maybe even your future self!).

Tekton has excellent [guidelines](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages)  on how to write a well formed commit message.

**Comment by adambkaplan** [comment]
/hold cancel

We can merge this now that Shipwright v0.16.0 has been released.

**Review by adambkaplan — APPROVED** [review]
/lgtm

Looks like it is working now, all tests pass!
