### PR TITLE
Operator should not delete CRDs

### LINKED ISSUE #173: [BUG] Operator RBAC Permissions are overly broad
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kubernetes Version

Kubernetes 1.24 or higher.

### Shipwright Version

v0.12.0

### Current Behavior

The Shipwright operator is granted RBAC permissions that are incredibly broad - it is effectively granted permission to be the "admin" over any workload and service account. This poses a security risk if the operator's service account token is leaked/exposed.

Snippet from `kubectl describe clusterrole` that is generated by OLM for the operator:

```
  Resources                                                             Non-Resource URLs  Resource Names                          Verbs
  ---------                                                             -----------------  --------------                          -----
  events                                                                []                 []                                      [create delete get list patch update watch]
  limitranges                                                           []                 []                                      [create delete get list patch update watch]
  namespaces                                                            []                 []                                      [create delete get list patch update watch]
  services                                                              []                 []                                      [create delete get list patch update watch]
  validatingwebhookconfigurations.admissionregistration.k8s.io/v1beta1  []                 []                                      [create delete get list patch update watch]
  validatingwebhookconfigurations.admissionregistration.k8s.io          []                 []                                      [create delete get list patch update watch]
  pods                                                                  []                 []                                      [get list watch create delete patch update]
  secrets                                                               []                 []                                      [get list watch create delete patch update]
  configmaps                                                            []                 []                                      [list get create update delete patch watch]
```

### Expected Behavior

The operator's service account should adhere to the "principle of least privilege" - it should only be granted the minimal set of RBAC permissions to operate, and nothing more.

Some Kubernetes admission controllers (that are enabled by default in some distributions) can expand what is required for "least privilege":

- [OwnerReferencesEnforcement](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement): controllers that set owner references on an object must have "delete" permission for said object.
- General [privilege escalation prevention](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#privilege-escalation-prevention-and-bootstrapping) built into the RBAC system.

### Steps To Reproduce

1. Deploy the Shipwright operator v0.12.0.
2. Inspect the permissions granted to the operator's service account. 

### Anything else?

Introduced in https://github.com/shipwright-io/operator/commit/64baf78c0427de606112b033ff0c736391a39ef7

### PR DESCRIPTION
**Pull request by jkhelil**
# Changes

- Filter Crds before deleting resources because operator should not delete Crds when shipwright instance is deleted

Fixes #173 

# Submitter Checklist

- [x] Includes tests if functionality changed/was added
- [ ] Includes docs if changes are user-facing
- [x] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)
- [x] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/main/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes

```release-note
Shipwright's Build CRDs are no longer deleted when the `ShipwrightBuild` object is deleted.
```

### CODE REVIEW

File: controllers/default_test.go [hunk 1]
```diff
@@ -244,10 +244,10 @@ var _ = g.Describe("Reconcile default ShipwrightBuild installation", func() {
...
 
 			// Verify - check the behavior
-			test.CRDEventuallyRemoved(ctx, k8sClient, "builds.shipwright.io")
-			test.CRDEventuallyRemoved(ctx, k8sClient, "buildruns.shipwright.io")
-			test.CRDEventuallyRemoved(ctx, k8sClient, "buildstrategies.shipwright.io")
-			test.CRDEventuallyRemoved(ctx, k8sClient, "clusterbuildstrategies.shipwright.io")
+			test.CRDEventuallyExists(ctx, k8sClient, "builds.shipwright.io")
+			test.CRDEventuallyExists(ctx, k8sClient, "buildruns.shipwright.io")
+			test.CRDEventuallyExists(ctx, k8sClient, "buildstrategies.shipwright.io")
+			test.CRDEventuallyExists(ctx, k8sClient, "clusterbuildstrategies.shipwright.io")
```
Comment (adambkaplan) [inline controllers/default_test.go:250]: I wonder if we should introduce a wait period before checking that the CRDs still exist?

File: controllers/default_test.go
Comment (adambkaplan) [inline controllers/default_test.go:1]: The `AfterEach` for this set of tests should delete the `*.shipwright.io` CRD instances. I think the tests previously relied on the delete behavior to tear down the CRD instance each time.

**Review by adambkaplan — CHANGES_REQUESTED** [review]
/approve

Giving :+1: on this fix going in. I only ask that my comment on `default_test.go` be addressed before merging.

File: controllers/default_test.go (hunk 1 above)
Comment (jkhelil) [reply controllers/default_test.go:250]: @adambkaplan The test is passing without the wait period, we do the same for the deployment and rbac and those tests had been working since the begining.
https://github.com/shipwright-io/operator/blob/main/controllers/default_test.go#L222

File: controllers/default_test.go
Comment (jkhelil) [reply controllers/default_test.go:1]: @adambkaplan Should we care about not deleteing the CRDs on tear down if the cluster is been stopped/deleed

**Comment by adambkaplan** [comment]
/lgtm

I am going to merge this as-is. Any additional work regarding test setup/teardown can be addressed in a follow-up pull request.

**Comment by adambkaplan** [comment]
Fixes #174
